name: "CI Nix"
# This workflow tests the library crate using Nix.
# Since this is a library (not a binary), `nix run` executes our test runner
# which builds the library and runs all tests in a reproducible Nix environment.
on:
  pull_request:
  push:
jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop -c rustc --version
      - name: Run tests via Nix
        run: nix run
